### ISSUE TITLE
Unable to build using make

### ISSUE THREAD

**Issue by techhat** [nbari/epazote#1]
I'm not used to installing Go packages, so I'm a little out of my element here. After downloading and unpacking the tarball, I'm trying to install via `make`:
```
[jhall@dufresne nbari-epazote-502682b]$ echo $GOPATH
/home/jhall/packages/epazote/nbari-epazote-502682b
[jhall@dufresne nbari-epazote-502682b]$ pwd
/home/jhall/packages/epazote/src/nbari-epazote-502682b
[jhall@dufresne nbari-epazote-502682b]$ make
go get
go install: no install location for directory /home/jhall/packages/epazote/src/nbari-epazote-502682b outside GOPATH
	For more details see: go help gopath
Makefile:14: recipe for target 'get' failed
make: *** [get] Error 1
[jhall@dufresne nbari-epazote-502682b]$ 
```
What am I missing here?

**Comment by nbari** [comment]
Hi, for simplicity you can get the binary from here: https://bintray.com/nbari/epazote/epazote/1.5.2/view

If you are using [FreeBSD](https://www.freebsd.org/) you can install it from the ports or by doing:

    pkg install epazote


To compile from source, you need to set your ``go`` environment, more detailed info here: https://golang.org/doc/install

In short what you could do is:

1. install go https://golang.org/dl/
2. ``mkdir /home/jhall/projects/go``
3. ``cd /home/jhall/projects/go``
4. ``mkdir bin pkg src``
5. ``mkdir -p src/github.com/nbari``
6. mv epazote source to ``/home/jhall/projects/go/src/github.com/nbari/epazote``
7. ``cd /home/jhall/projects/go/src/github.com/nbari/epazote`` and type ``make``

If you con't want to use the Makefile, you can also do ``go build -o epazote cmd/epazote/main.go`` 

If have further questions please let me know.

**Comment by techhat** [comment]
Thanks @nbari. I'm trying to put together an [AUR](https://aur.archlinux.org/) package for Arch, so it would be ideal to build from source. I'll try out those steps and see what I get.

**Comment by nbari** [comment]
Maybe this can help: https://github.com/freebsd/freebsd-ports/blob/07ba7ad0a667e3f2a6837994476f31ea5e396f31/sysutils/epazote/Makefile

Is the Makefile for the FreeBSD ports basically fetches all dependencies, create some hashes and instead of using ``make`` uses ``go build``

**Comment by nbari** [comment]
Probably want to use version 2 now https://github.com/epazote/epazote
